name: Build and Deploy Jekyll

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Replace with your desired Ruby version

      - name: Install Jekyll and Bundler
        run: |
          gem install bundler jekyll
          bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: actions/deploy@v1
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          repository-name: ${{ github.repository }}
          branch: gh-pages
          folder: _site
